# Site settings
title: My Site
email: yashjirbhar24gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yashjain24.github.io" # the base hostname & protocol for your site

# User setting
owner: "Yash Jain"
email: "yashjirbhar24@gmail.com
facebook_username: "jain.yash.24"
twitter_username: "yash__jain__"
github_username: "yashjain24"
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: "8192007320"
copyright: "yashjain24"

# API settings
google_api_key:

# Build settings
markdown: kramdown
